'Job' is not recognized as an internal or external command,
operable program or batch file.
'Job' is not recognized as an internal or external command,
operable program or batch file.
'Job' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 28, in <module>
    print(json.loads(input))
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 29, in <module>
    content = json.loads(input)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 10, in <module>
    content = json.loads(input)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 30, in <module>
    fixJson(content)
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 9, in fixJson
    if jf["flag"] == "true":
TypeError: string indices must be integers
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 30, in <module>
    fixJson(content)
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 9, in fixJson
    if jf["flag"] == "true":
TypeError: string indices must be integers
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 30, in <module>
    fixJson(content)
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 9, in fixJson
    if jf["flag"] == "true":
TypeError: string indices must be integers
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 30, in <module>
    fixJson(content)
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 9, in fixJson
    if jf["flag"] == "true":
TypeError: string indices must be integers
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 30, in <module>
    fixJson(content)
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 9, in fixJson
    if jf["flag"] == "true":
TypeError: string indices must be integers
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 32, in <module>
    fixJson(content)
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 9, in fixJson
    if jf["flag"] == "true":
TypeError: string indices must be integers
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 37, in <module>
    fixJson(content)
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 10, in fixJson
    if jf["flag"] == "true":
TypeError: string indices must be integers
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 36, in <module>
    print(content["flag"])
TypeError: string indices must be integers
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 37, in <module>
    print(content["flag"])
TypeError: string indices must be integers
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 37, in <module>
    print(content("flag"))
TypeError: 'str' object is not callable
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 36, in <module>
    print(content.keys())
AttributeError: 'str' object has no attribute 'keys'
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 37, in <module>
    print(content["flag"])
TypeError: string indices must be integers
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 11, in <module>
    content = json.loads(json.loads(base64.b64decode(input)))
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
The command line is too long.
The command line is too long.
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 11, in <module>
    content = json.loads(json.loads(base64.b64decode(input)))
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
The command line is too long.
The command line is too long.
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 16, in <module>
    content = json.loads(json.loads(base64.b64decode(input)))
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 16, in <module>
    content = json.loads(json.loads(base64.b64decode(input)))
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 16, in <module>
    content = json.loads(json.loads(base64.b64decode(input)))
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 16, in <module>
    content = json.loads(json.loads(base64.b64decode(input)))
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 16, in <module>
    content = json.loads(json.loads(base64.b64decode(input)))
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 24, in <module>
    content = json.loads(content)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 24, in <module>
    content = json.loads(content)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 24, in <module>
    content = json.loads(content)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 24, in <module>
    content = json.loads(content)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 24, in <module>
    content = json.loads(content)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The command line is too long.
The command line is too long.
The command line is too long.
The command line is too long.
The command line is too long.
The command line is too long.
The command line is too long.
The command line is too long.
The command line is too long.
The command line is too long.
The command line is too long.
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 10, in <module>
    input = sys.argv[1]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 10, in <module>
    input = sys.argv[1]
IndexError: list index out of range
The command line is too long.
The command line is too long.
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 16, in <module>
    content=base64.b64decode(input)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 16, in <module>
    content=base64.b64decode(input)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4
Traceback (most recent call last):
  File "C:\xampp\htdocs\ingebau\formulario\python\test.py", line 16, in <module>
    content=base64.b64decode(input)
  File "C:\Users\darka\AppData\Local\Programs\Python\Python39\lib\base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Invalid base64-encoded string: number of data characters (5) cannot be 1 more than a multiple of 4
